# Generated by Django 5.2.8 on 2025-11-23 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_returnable', models.BooleanField(default=False)),
                ('return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('return_status', models.CharField(choices=[('NONE', 'Not Returnable'), ('PENDING', 'Pending'), ('PARTIAL', 'Partially Returned'), ('CLEARED', 'Cleared')], default='NONE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='threadApp.threadnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='threadApp.threadnode')),
            ],
        ),
    ]
