# Generated by Django 5.2.8 on 2025-11-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadnode',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Running balance after this transaction', max_digits=12),
        ),
        migrations.AddField(
            model_name='threadnode',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
